# Generated by Django 2.2.5 on 2020-02-14 09:55

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Organisation',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('organisation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venter.Organisation')),
            ],
            options={
                'verbose_name_plural': 'User Category',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckpt_date', models.DateTimeField(default=datetime.datetime.now)),
                ('has_prediction', models.BooleanField(default=False)),
                ('output_file_json', models.FileField(blank=True, max_length=255, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('wordcloud_data', models.FileField(blank=True, max_length=255, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('organisation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venter.Organisation')),
            ],
            options={
                'verbose_name_plural': 'File',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('organisation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venter.Organisation')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_complaint', models.CharField(max_length=1000)),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venter.UserCategory')),
            ],
            options={
                'verbose_name_plural': 'User Complaint',
                'unique_together': {('user_category', 'user_complaint')},
            },
        ),
    ]
